random_seed: 42
data_file: 'preprocessed_data.npz'
validation_split: 0.1
batch_size: 4096
num_epochs: 50
learning_rate: 0.001
weight_decay: 1e-5
max_lr: 0.01
embedding_dim: 64
hidden_dim: 128
n_layers: 3
dropout: 0.2
patience: 5
top_k: 10